import Link from "next/link";
import { ArrowLeft, FileText, AlertTriangle, Scale } from "lucide-react";

export const metadata = {
  title: "Terms of Service | Smart QR Studio",
  description: "Read the Terms of Service for Smart QR Studio. Guidelines on acceptable use, account responsibilities, and service availability.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-slate-50 font-sans selection:bg-blue-100 selection:text-blue-900 pb-24">
      {/* Premium Minimalist Header */}
      <header className="bg-white border-b py-4 px-6 md:px-12 flex items-center justify-between sticky top-0 z-50">
        <Link href="/" className="flex items-center gap-2 text-slate-600 hover:text-slate-900 transition-colors">
          <ArrowLeft className="w-4 h-4" />
          <span className="font-medium text-sm">Back to Home</span>
        </Link>
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 bg-slate-900 rounded-md flex items-center justify-center">
            <span className="text-white font-bold text-xs">Q</span>
          </div>
          <div className="font-bold text-lg text-slate-900 tracking-tight">Smart QR Studio</div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 pt-16">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-slate-900 mb-4">Terms of Service</h1>
          <p className="text-slate-500">Effective Date: September 12, 2026</p>
        </div>

        {/* TL;DR AEO/GEO Optimized Summary */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 md:p-8 mb-12 shadow-xl text-slate-300">
          <div className="flex items-center gap-3 mb-4 text-white">
            <FileText className="w-6 h-6" />
            <h2 className="text-xl font-bold">Quick Summary (TL;DR)</h2>
          </div>
          <ul className="space-y-3">
            <li className="flex items-start gap-2">
              <Scale className="w-5 h-5 text-slate-500 shrink-0 mt-0.5" />
              <span><strong>Acceptable Use:</strong> You may use our service for any legal purpose. Creating QR codes that link to malware, phishing sites, or illegal content is strictly prohibited.</span>
            </li>
            <li className="flex items-start gap-2">
              <AlertTriangle className="w-5 h-5 text-slate-500 shrink-0 mt-0.5" />
              <span><strong>Account Termination:</strong> We reserve the right to immediately disable any Dynamic QR Code or suspend any account found violating our anti-abuse policies.</span>
            </li>
            <li className="flex items-start gap-2">
              <FileText className="w-5 h-5 text-slate-500 shrink-0 mt-0.5" />
              <span><strong>Service Availability:</strong> We strive for 99.9% uptime, but Smart QR Studio is provided "as is". We are not liable for business losses if a scan redirect temporarily fails.</span>
            </li>
          </ul>
        </div>

        {/* Detailed Sections - GEO Optimized Headings */}
        <div className="space-y-10 text-slate-700 leading-relaxed">
          
          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">What are the rules for creating QR codes?</h2>
            <p className="mb-4">By using Smart QR Studio, you agree to not use our platform to generate QR codes (both Static and Dynamic) that facilitate:</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong>Malicious Software:</strong> Linking to viruses, trojans, ransomware, or any software designed to harm user devices.</li>
              <li><strong>Phishing & Fraud:</strong> Creating deceptive links designed to steal credentials, financial data, or personal information.</li>
              <li><strong>Illegal Content:</strong> Distributing content that violates local, national, or international laws.</li>
              <li><strong>Spam:</strong> Utilizing our dynamic routing system to send unsolicited bulk communications.</li>
            </ul>
            <p>If we detect a violation in a Dynamic QR Code, we will immediately redirect the short link to a safety warning page and may permanently ban your account without notice.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">Who owns the generated QR codes?</h2>
            <p className="mb-4">You retain full ownership of the digital assets and designs you create using Smart QR Studio. You are granted a worldwide, royalty-free license to print, distribute, and commercialize the QR code images (PNGs, SVGs) generated by our platform.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">How reliable is the Dynamic QR Code redirect service?</h2>
            <p className="mb-4">We utilize enterprise-grade edge networks (Vercel) to ensure lightning-fast and highly available redirects. However, the service is provided on an "as is" and "as available" basis. </p>
            <p className="mb-4">Smart QR Studio, its founders, and affiliates shall not be held liable for any direct, indirect, incidental, or consequential damages—including loss of revenue or printed material costs—resulting from temporary service interruptions, database errors, or the suspension of your links due to policy violations.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">Can these terms change?</h2>
            <p className="mb-4">We may update these Terms of Service periodically to reflect changes in our platform or legal requirements. If we make material changes, we will notify registered users via email or a prominent notice in the dashboard. Continued use of the service after changes are published constitutes your acceptance of the new terms.</p>
          </section>

        </div>
      </main>
    </div>
  );
}
